### ISSUE TITLE
Ukoly 1.1 - 1.5

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#1]
@andywaltlova Prosila bych o kontrolu úkolů k první lekci.

**Comment by andywaltlova** [comment]
### 1. úkol :heavy_check_mark: 

- Řešení super, funguje tak jak má
- ❗ Upozornění: pokud je proměnná typu bool, neměla by jsi psát `if promenna == True:` (řádek 11) a ani  ` promenna is True` (to neni tvuj pripad), preferovaná varianta je zkrátka napsat `if promenna:` , malý příklad:

```python
pravda = True
if pravda:
    print('Je to pravda!')
else:
    print('Neni to pravda!')'
```

Případně můžeš použít klíčové slovo `not`:
```python
pravda = True
if not pravda:  # negace False je True
    print('Neni to pravda!')
else:
    print('Je to pravda!')'
```

Je to stejné jako když kontroluješ například `if 2>3:` , což samozřejmě není pravda, ale za celým výrazem `2>3` si můžeš zkrátka představit `False` hodnotu :)
 **NEnapíšes to přece takto**:
```python
if 2>3 == True: # to vypada divne ne? 😉 
    print('Je to pravda!')
else:
    print('Neni to pravda!')
```

### 2. úkol :heavy_check_mark: 

- Super řešení 👍 
- řádký 8, 9 jsou zbytečné, proměnným nemusíš přiřazovat nejdřív nuly a pak je v zápětí hned přepsat hodnotou z input funkce :)

### 3. úkol :heavy_check_mark: 

- Super, jen ti tady chybí použití jedné funkce, pomocí které zjistíš počet místností (délku seznamu)

> Firma eviduje volné meetingové místnosti v průběhu dne ve slovníku. Klíč slovníku je hodina a hodnotou slovníku seznam zasedaček, které jsou v té době volné. Napiš software, který se zeptá uživatele na číslo hodiny, kdy chce zamluvit meeting room. Poté **vypíše počet volných místností**, které jsou k dispozici.

### 4. úkol :heavy_check_mark: 

- Skvélé, nemám co vytknout :)

### 5. úkol :heavy_check_mark: 
- Pěkné řešení
- V tomto případě je zbytečný pouze řádek 18, kdy total proměnná může klidně vzniknout až při sčítání. Řádky 16 a 17 jsou potřeba protože kdyby neprošel ani jeden if, tak musí proměnné existovat kvůli sčítání na řádku 23. (stačila by celkově i jedna proměnná do které by si v ifech jen přičítala čísla).

---

Poprosím o úpravu 1 a 3 příkladu. U 1. se prosím zbav toho porovnávání `== True`, u 3. pak stačí přidat vhodnou funkci na zjištění delky seznamu.

Skvělá práce, jen tak dál 👍

**Comment by Kruto-n** [comment]
@andywaltlova Ahoj, opravila jsem 1.1. a 1.3, akorát u 1.1 jsem měla špatně pojmenovaný commit (mela jsem tam pořád, že je to úloha 1.5 od minula)  a pak jsem nevěděla, jak to spravit a tak jsem tam akorát udělala malou nepodstatnou změnu a pojmenovala commit správně. Akorát mi nedošlo, že tam teď nevidíš zvýrazněnou tu změnu. Příště musím dávat větší pozor.

**Comment by andywaltlova** [comment]
Super, v historii commitu vidim vsechny  zmeny, pak se vzdy stejne divam celkove na cely opraveny soubor ;} Uzaviram issue, ukoly povazuji za splnene. Komentovat jde i po uzavreni :)
