### ISSUE TITLE
Lekce 2

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#2]
@andywaltlova Ahoj, odevzdávám úkoly k druhé lekci, ale nejsou úplně v top stavu. U program06 nevím, jak se zbavit toho, aby to po vypsání všech států na konci vypsalo ještě neznámý region. U program07 si vůbec nevím rady, zkoušela jsem to několika způsoby a vždycky mi to hodí "str object cannot be interpreted as an integer". Zbytek by snad měl nějak fungovat.

**Comment by andywaltlova** [comment]
### 6. úkol
-  Konstrukce  `for` + `else` funguje tak, ze pokud nenastane `break` ve for cyklu, vypise se to co je v `else` vetvi. Priklad:
```python
for name in ['Karel','Jana']:
    print(name)
else:
    print('Text ktery se vypise vzdy')

print()  # pro prehlednost oddeleni printu

for name in ['Karel','Jana']:
    if name == 'Karel':
        print('Karel se nasel!')
        break
else:
    print('Text ktery se vypise jen kdyz se Karel nenasel')
    # protoze kdyz se karel najde, udela se break (vyskoci se z cyklu predtim nez se vycerpaji vsechny veci z listu)
```
- V tomto ukolu ti tato konstrukce moc nepomuze, protoze stejne potrebujes vypsat vsechny regiony.
- Bud si muzes napriklad drzet navic nejakou promennou `region_found` ktera je pred for cyklem nastavena na `False` a pokud se najde region zmenis ji na `True`, pod for cyklem pak tuto promennou jen zkontrolujes a pokud v ni je stale `False` tak vis ze jsi na zadny znamy region nenarazila.
- Nebo si muzes misto okamziteho vypisovani davat ty jmena do listu, pokud pod for cyklem mas list prazdny, vis ze se zadny region nenasel. Kdyz je neprazdny tak je vypises.

### 7. úkol
- zkusim ti napovedet textovym popisem co musis upravit u 6 aby si docilila toho co se chce v tomto prikladu

```python
# Sestav slovník, který bude obsahovat celkové počty obyvatel pro jednotlivé subregiony v daném regionu.
# Například pokud uživatel zadá Europe, tak by měl být výsledek následující.

oblast = input(f"Jaky Vas zajima region?")
# Budes potrebovat nejakou promennou pro vysledny slovnik (jmeno = {})
for item in staty:
    znamy = item["region"] == oblast
    if znamy:
        # Tady uz vime ze se jedna o stejny region (napriklad ta Evropa)
        # Ve slovniku mame mit subregiony jako klice, a populaci jako hodnotu
        # Pokud subregion (item['subregion']) jeste ve slovniku neni, chci ho tam pridat s danou populaci (item['population'])
        # novy klic pridas takto: slovnik[novy_klic] = hodnota
        # Pokud tam je, chci uz k existujicimu klici (stale item['subregion']) pricist danou populaci (item['population'])
        print(f"Subregion: {item['subregion']}") # print muze byt treba kontrolni
```
### 8. úkol ✔️
- Uznam ti to, ale ❗ 
    - Radky 17-22 (funkce `price`) , idealni je skladat si vsechny definice funkci nahoru pod sebe, prispiva to k prehlednejsimu a vice citelnejsimu kodu. Zkratka oddelit hlavni kod ktery se vykonava, od samotnych definici :) (takze i ten input a replace nahore zase naopak presunout pod definice)
    - Samotnou funkci pak chces vlastne volat v te podmince, kdy uz vis ze je telefoni cislo spravne, tedy volani funkce odsadit o kousek vpravo. Ale je fajn ze sis definovala tu promennou `message` aby ti to nehazelo error ikdyz to volani mas mimo if :) Jen by davalo vetsi smysl volat to uvnitr ifu, protoze to ze je cislo nevalidni uz vlastne vypise ta funkce predtim.
   
### 9. úkol ✔️
- Krasne, tady sis poradila pekne :)
- Jenom napoveda: existuji funkce `sum` a `len`, takze misto vlastni funkce pro prumer, stacilo udelat:
```python
# Hned jako prvni prikaz ve funkci ohodnot_studenta
jmeno = student.pop('Jméno')  # Ze slovniku vyhodi ten jediny neciselny klic, a jeho hodnotu ulozi do promenne jmeno
# Prumer pak uz muzes spocitat pres funkce, protoze ti tam neprekazi to jmeno
prumer = sum(student.values())/len(student)
# ...
# pri vypisyupak uz muzes pouzivat jen tu promennou jmeno
```

### 10.úkol ✔️
- Taky ti to uznam, reseni pekne, jen pozor, trosku jsi si upravila tu praci s parametry `konference` a `newsletter`.
- Zadani ti melo napovedet, ze defaultni hodnota u tech dvou parametru je `konference=False, newsletter=False` (to mas v poradku)
- Pak uz s tim vlastne nepracujes, protoze funkci vzdy predavas neco na tento zpusob `konference='ano', newsletter='ne'`, tedy funkce pak vlastne nepracuje s bool hodnotami, ale se stringy :) Zadani pravdepodobne pocitalo s tim, ze napises jen definici funkce, nemusela si se starat i o to jak se ta funkce fakticky zavola (odkud ty hodnoty vezme), takze to te mozna vic zmatlo.
- Ve zkratce, funkce mela dostat tyto dva parametry jako bool hodnoty a pak body pridelovat na zaklade podminky ve stylu `if konference:` prictu body. 
- To odkud se vzalo to `True` a `False`, muzes si treba predstavit ze pred volanim funkce jsme si `"ano"` predelali na `True` a `"ne"` na `False`.

```python
# A tenhle else vlastne nic nedela :) 
else:
        body += 0
```
---

Zkus upravit tu 6 a 7 podle navodu co jsem psala :) Klidne mi sem hod komentar kdyz si nebudes vedet rady!
Jinak skvela prace 👍

**Comment by Kruto-n** [comment]
@andywaltlova Ahoj, díky za rady. Zkusila jsem to nějak opravit - nevím, jestli to je úplně ideální, ale nějak tak to funguje 😆

**Comment by andywaltlova** [comment]
Ahoj! 

### 6. úkol
- super, ze jsi pridala promennou `region_found`, akorat ty dva for cykly moc nedavaji smysl, k cemu potrebujes ten druhy? :)

```python
oblast = input(f"Jaky Vas zajima region?")
region_found = 0 # muzes klidne dat False

for item in staty:
    if item["region"] == oblast: # tady uz vime ze region existuje
        region_found = True
        # ten print itemu tady muzes nechat, protoze podle podminky vime ze region existuje, proto chceme print
    else: # zbytecny cely else, pokud podminka neni splnena tak v promenne mam porad False / nebo tu nulu
        region_found = False

# Jaky ma ten druhy for cyklus ucel? Print itemu prece uz muzes udelat v prvnim :) 
# Jedine co potrebujes zachovat je ta podminka if region_found, akorat ji upravit na if not region_found:
# aby jsi mohla vypsat ze se jedna o neznamy region -> neznamy region pozname podle toho ze v region_found zustane False
# takze uz pak jen udelej 
# if not region_found: ( kdyz zustane v promenne False tak je to if not False a not False je True) 
#     print('Neznamy region')

```

### 7.úkol ✔️ 
- tento ti uznam, si blizko ke spravnemu reseni :) Z komentare niz by melo byt asi jasne, co je tam navic :)
```python
oblast = input(f"Jaky Vas zajima region?")
regiony = {} # super, to je presne to co jsme potrebovali
for item in staty:
    znamy = item["region"] == oblast
    if znamy:
        for key, value in regiony: # tento for cyklus nefunguje, protoze slovnik je vzdy prazdny (nic se neprochazi - staci dat pryc)
            if item["subregion"] in regiony:
                regiony[item["subregion"]] += item["population"]
            else:
                regiony[item["subregion"]] = item["population"]
        print(f"Subregion: {item['subregion']} , population : {item['population']}") # toto funguje, akorat nedostaneme ten soucet

# kdyz odstranis ten radek 496 a nechas jen if a else, budou se ti do slovniku vkladat klice
# ted se tam nevkladaji protoze regiony je prazdny slovnik, tedy for key,value in {} nikdy neprojde, protoze nema co prochazet
# pak uz jen tady staci dat print(regiony)
```
---
Tu 6, jeste prosim dooprav :) V komentari jsem ti snad i dost napovedela - potrebuji jen videt ze chapes co se v tom programu deje, k cemu je dobra ta promenna `region_found` . 

U 7 jsi to zvladla skoro cele dobre - tam uz te s opravou trapit nebudu, z komentare by melo byt jasne proc to vkladani do slovniku nefunguje.

Jinak kdyz ti tam treba pisu otazky, snazim te donutit zamyslet se nad ucelem toho kousku kodu - jestli je tam potreba, jestli je to vhodne udelane, navhrnout jiny pristup. Urcite to neber nijak spatne - takto se i ve firme delaji mezi kolegy code reviews :)

Verim ze ten posledni priklad zvladnes dokoncit! 💪

**Comment by Kruto-n** [comment]
@andywaltlova Tak jsem znova zkusila 6 :D

**Comment by andywaltlova** [comment]
No paráda! :)

Takže druhý týden máš hotový 🥳
