### ISSUE TITLE
3. lekce - úkoly

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#3]
@andywaltlova Ahoj, odevzdávám úkoly z třetí lekce :) .

**Comment by andywaltlova** [comment]
### 11 .úkol ✔️ 
- Super 👍 
- hezky sis vytvorila i nepovinny argument pro tu dostupnost, ted vlastne muzes vytvorit i auto ktere je nedostupne hned od jeho vytvoreni :)
- ty kilometry asi klidne muzes davat rovnou jako čislo :)
### 12 .úkol ✔️ 
- EDIT: po oprave OK
- Funguje tak jak má, jen dvě kosmeticke připomínky:
    - `self.dostupnost == True` , podobne jako v ukolu z prvniho tydne, dej pryc `==True`, v promenne dostupnost uz je bool hodnota, je to tedy zbytecne porovnavat :)
    - ve funkci `pujc_auto()` by se retezec mel **vracet** ne printovat, potom ti to pri vypisu dela neporadek -> vytiskne ti to i `None` hodnotu (protoze kdyz chybi `return`, je to jako kdyby tam bylo `return None`) -> vlastne by o melo fungovat stejne jako funkce `get_info()`
![image](https://user-images.githubusercontent.com/19702477/111063857-2cc33300-84b1-11eb-881c-61390f91f769.png)

### 13 .úkol ✔️ 
- Paráda 👍 
- na radku 17 `self.dny = dny` ani nepotrebujes, protoze s temi dny pocitas jen pri vraceni :), jedine ze by si chtela uchovavat i informaci o tom kolik dni bylo auto pujceno (pri poslednim pujceni)
### 14 .úkol ✔️ 
- Skvělé, nemám co dodat :-)
### 15 .úkol ✔️ 
- Super !
- Moc pekne si napsala ty podminky, prijde mi to dobre citelne :)

---
U 12. staci opravit ty dve kosmeticke veci :)

**Comment by Kruto-n** [comment]
@andywaltlova Díky za kontrolu, 12. opravena :)

**Comment by andywaltlova** [comment]
To bylo rychlé ! :) Takže i 3 týden máš splněn ! 👍
