### ISSUE TITLE
5

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#5]
@andywaltlova Ahoj Andy, odevzdávám úkoly k 5. lekci, všechno ⭐s n a d⭐ funguje, ale u posledního úkolu neumím udělat novou tabulku 😅

**Comment by andywaltlova** [comment]
### 21 ✔️ 
- Super, neni co dodat 👍 
### 22 ✔️ 
- Taky spravne reseni
### 23 ✔️ 
- Popravde me tady trochu prekvapilo ze pouzivas podminky uvnitr `.loc[]` (protoze jsme si to primo neukazovali) ale proc ne, funguje to a navic si rovnou vyberes jen sloupce ktere chces 👍  
### 24 ✔️ 
- Taky super, s podminkami ocividne nemas problem :-)
### 25 ✔️ 
- tady je tou novou tabulkou hlavne mysleno, aby sis stale neprepisovala ten samy dataframe, takze pokud sis udelala `den = temperature.loc[(temperature["Day"] == 13)]` tak v puvodnim dataframu temperature mas porad vsechny data, a v promenne den uz jen ty vyfiltrovana, takze je to jakoby nova tabulka.
- V ukolu ti tedy chybi akorat ten dotaz v posledni odrazce zadani
> Pro data z předchozího dotazu napiš dotaz na řádky ve městech (sloupec City) Washington a Phiadelphia.
- ukol ti uznam i bez toho, protoze vidim ze podminky psat umis, takze mi nedava moc smysl nutit te to dodelat :)

---
Tyden 5 tedy uzaviram 🥳

**Comment by Kruto-n** [comment]
@andywaltlova hehe, u 23 jsem použila .loc nejdřív omylem, ale všimla jsem si, že to funguje, tak jsem ho tam nechala a doufala, že to nebude ničemu vadit 😅 Ráda bych řekla něco ve smyslu, že se navíc sama vzdělávam ještě třeba v dokumentaci ale naneštěstí ne - já jsem ráda, že jsem ráda 😅 😅 😅 Moc díky za opravu ❤️
