### ISSUE TITLE
Andy, pomoc!

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#6]
@andywaltlova Ahoj! Dělám úkol 1 ze 6. lekce, ale mám problém, protože když si vypíšu head těch platů a měst, tak tam mám sloupec cislo_zamestnance úplně prázdný :( Ani NaN tam nemám :D Nezměnily se nějak odkazy na ty soubory?

**Comment by andywaltlova** [comment]
Ahoj, 
kdyz to stahnu podle toho co je v [zadani](https://github.com/pesikj/python-012021/blob/master/zadani/6/priklad26.md), tak tam normalne vsechny pozadovane hodnoty mam. 

Deje se ti to az po pokusu o spojeni tech tabulek? Kdyztak mi do githubu pridej ten kod co nefunguje, takto se tezko odhaduje kde je chyba :) 

```python
# tento kod mi funguje  a normalne vypisuje data i s cisly zamestnancu
import pandas as pd
import wget
# odkaz jsem vzala ten ze zadani
wget.download("https://raw.githubusercontent.com/pesikj/python-012021/master/zadani/6/zam_praha.csv")

praha = pd.read_csv('zam_praha.csv')
praha['mesto'] = 'Praha'
print(praha.head())
```

**Comment by Kruto-n** [comment]
@andywaltlova  Ahoj Andy, už mi to jde, ukázalo se, že jsem měla překlep ve slově 😅 , odevzdávám úkoly z 6. lekce, akorát u 5. příkladu vůbec nevím, kde mám sešit v excelu s tou tabulkou hledat? Zpětné načtení funguje, takže někam se to načetlo, ale kam 😆

**Comment by andywaltlova** [comment]
### 26 ✔️ 
- Super, takto je to v poradku :)
### 27 ✔️ 
- Taky super, groupby mas koukam zmaknute 👍 
### 28 ✔️ 
- Taky skvele , neni co dodat :)
### 29 ✔️ 
- Super ze si skusila filtrovani vice zpusoby (radky 6 a 7) 👍 
### 30 ✔️ 
- Dobre, ta tabulka my se ti mela ulozit do stejne slozky jako mas vypracovany ukol. Ten string predstavuje cestu k souboru, takze kdyz tam mas jen `'hours.xlsx'` tak je to stejna slozka jako skript, pokud bys mela napriklad `'data/hours.xlsx'` ( na windows `'data\\hours.xlsx'`),tak by se soubor ulozil do slozky data - ta tedy musi existovat).

Tyden 6 tedy take hotovy 🥳
