### ISSUE TITLE
Úkoly 7

### ISSUE THREAD

**Issue by Kruto-n** [Kruto-n/python-012021#7]
@andywaltlova Odevzdávám úkkoly k 7. lekci, měly by fungovat, akorát u posledního úkolu nevím, jak udělat, aby mi ten boxplot ukazoval ta různá města :(

**Comment by andywaltlova** [comment]
### 31 ✔️ 
- Super 👍 
### 32 ✔️ 
- Taky není co dodat, graf je přehledný :)
### 33 ✔️ 
- Dobree, jenom tam nevidim ze sis to zkusila i predtim nez si to prevedla na datetime, pripadne nejaky komentar co se zmenilo by neuskodil - ale verim ze sis to zkusila.
### 34 ✔️ 
-  Super, neni co vytknout 
### 35 ✔️ 
- po oprave OK
- Tady je to jen malickost, pouzivas spravny atribut `by`, ale spatnou funkci. Ty podgrafy se spravne vykresli kdyz pouzijes `cities.boxplot(column=... , by=...)`. Koukni na priklad v [dokumentaci](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.boxplot.html). 
- Uznavam ze je to trochu neintuitivni, ale myslim ze funkce `plot` nema zadny `by` parametr -> nenasla jsem v dokumentaci ani u [pandasu](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html) ani u [matplotlibu](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html). Zaroven ale nezahlasi zadnou chybu, proste na nej nereaguje.

**Comment by Kruto-n** [comment]
@andywaltlova  díky, už by ta pětka měla fungovat :)

**Comment by andywaltlova** [comment]
Super, takze 7 tyden uzaviram :)
